config/routes.rb
Rails.application.routes.draw do
  root "pages#index"
  resources :application_forms, only: [:new, :create, :index]
  resources :members, only: :index
end

app/models/application_form.rb
class ApplicationForm < ApplicationRecord
  include EmailValidation

  validates :name, presence: true, uniqueness: true
  validates :company, presence: true
  validates :message, presence: true

  belongs_to :member, optional: true
  
  scope :with_email, -> (email) { where("email LIKE ?", "%#{email}%") }
  scope :submitted_by_member, -> (member) { where(member_id: member) }
  scope :start_of_the_til, -> (date) { where(:created_at => Date.today.beginning_of_day..date.to_date) }

  before_save :verify_email

  def self.search(params)
    if params[:member_email].present?
      submitted_by_member(params[:member_email])
    elsif params[:email].present?
      with_email(params[:email])
    elsif params[:date].present?
      start_of_the_year_to(params[:date])
    else
      all
    end
  end

  private
    def verify_email
      self.member = Member.find_by_email(self.email)
    end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/concerns/email_validation.rb
module EmailValidation
  extend ActiveSupport::Concern

  included do
    validates :email, presence: true, format: /\A([\w+\-]\.?)+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i
  end
end

app/models/member.rb
class Member < ApplicationRecord
  include EmailValidation
  validates :email, uniqueness: true
  has_many :application_forms
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/application_forms_controller.rb
class ApplicationFormsController < ApplicationController

  def index
    @application_forms = ApplicationForm.search(params)
  end

  def new
    @application_form = ApplicationForm.new
  end

  def create
    @application_form = ApplicationForm.new(application_form_params)

    if @application_form.save
      redirect_to root_path, notice: 'Application form was successfully created.'
    else
      render :new
    end
  end

  private
    # Only allow a list of trusted parameters through.
    def application_form_params
      params.require(:application_form).permit(:name, :email, :company, :message)
    end
end

app/controllers/members_controller.rb
class MembersController < ApplicationController
  def index
    @members = Member.all
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end
end

app/helpers/application_forms_helper.rb
module ApplicationFormsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/members_helper.rb
module MembersHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/application_forms/_form.html.haml
= form_for @application_form do |f|
  - if @application_form.errors.any?
    #error_explanation
      %h2= "#{pluralize(@application_form.errors.count, "error")} prohibited this application_form from being saved:"
      %ul
        - @application_form.errors.full_messages.each do |message|
          %li= message

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :email
    = f.text_field :email
  .field
    = f.label :company
    = f.text_field :company
  .field
    = f.label :message
    = f.text_field :message
  .actions
    = f.submit 'Save'

app/views/application_forms/index.html.haml
%h1 Application Forms
= form_tag application_forms_url, method: :get do
  = select_tag :member_email, options_from_collection_for_select(Member.all, "id", "email"), { include_blank: true }
  = label_tag(:email, "Search Email")
  = text_field_tag :email, params[:email]
  = label_tag(:date, "Search Date")
  = text_field_tag :date, params[:date]
  = submit_tag("Search", name: nil, class: "btn btn-primary")


%table.table
  %thead.thead-dark
    %tr
      %th Name
      %th Email
      %th Company
      %th Date

  %tbody
    - @application_forms.each do |application_form|
      %tr
        %td= application_form.name
        %td= application_form.email
        %td= application_form.company
        %td= application_form.created_at.strftime("%d/%m/%Y")

%br

app/views/application_forms/new.html.haml
%h1 New application_form

= render 'form'

= link_to 'Back', application_forms_path

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{charset: "utf-8"}
    %meta{content: "IE=edge", "http-equiv" => "X-UA-Compatible"}
    %meta{content: "width=device-width, initial-scale=1", name: "viewport"}
    %meta{content: "", name: "description"}
    %meta{content: "", name: "author"}
    %title Careersgapp

    / HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries
    /[if lt IE 9]
      = javascript_include_tag "https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js", "https://oss.maxcdn.com/respond/1.4.2/respond.min.js"

    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track' => 'reload'
    = csrf_meta_tags
  %body
    %nav.navbar.navbar-inverse.navbar-fixed-top{role: "navigation"}
      .container
        .navbar-header
          = link_to "Careersgapp", "/", class: "navbar-brand"
    .container-fluid
      - flash.each do |name, msg|
        = content_tag :div, class: "alert alert-#{name == :error ? "danger" : "success" } alert-dismissable", role: "alert" do
          %button.close{type: "button", data: {dismiss: "alert"} }
            %span{aria: {hidden: "true"} } &times;
            %span.sr-only Close
          = msg
      .container
        = yield

app/views/members/index.html.haml
.container
  %h1 Members#index
  %p Find me in app/views/members/index.html.haml
  %table.table
    %thead.thead-dark
      %tr
        %th{:scope => "col"} MemberId
        %th{:scope => "col"} Email
    %tbody
      - @members.each do |member|
        %tr
          %th{:scope => "row"}= member.id
          %td= member.email

app/views/pages/index.html.haml
= link_to "Application Form", new_application_form_path
= link_to "Application List", application_forms_path
= link_to "Members List", members_path